
theme = "my-onedark"

[editor]
line-number = "relative"
mouse = false
color-modes = true
rulers = [80]
indent-guides.render = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = ""
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
snippets = true
display-messages = true

# or control each character
[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
#space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
#tabpad = "·" # Tabs will look like "→···" (depending on tab width)



